plugins {
//    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id("com.gradleup.shadow") version "9.6.1"
    id 'io.micronaut.application' version '5.0.2'
    id 'io.micronaut.aot' version '5.0.2'
    id 'org.openjfx.javafxplugin' version '0.0.14'
}


version = "0.1"
group = "io.igx.fx"

repositories {
    mavenCentral()
}

micronaut {
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("io.igx.fx.*")
    }
//    aot {
    // Please review carefully the optimizations enabled below
    // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details

//        optimizeServiceLoading = false
//        convertYamlToJava = false
//        precomputeOperations = true
//        cacheEnvironment = true
//        optimizeClassLoading = true
//        deduceEnvironment = true
//        optimizeNetty = true
//        replaceLogbackXml = true
//    }
}

dependencies {
    runtimeOnly("ch.qos.logback:logback-classic")

    implementation 'io.micronaut:micronaut-http-client-jdk'
//    implementation 'io.micronaut:micronaut-http-client'
    runtimeOnly 'io.micronaut:micronaut-jackson-databind'
    compileOnly 'io.micronaut.reactor:micronaut-reactor:4.3.0'

    //implementation 'com.gluonhq:ignite-micronaut:1.2.2'
    compileOnly 'jakarta.validation:jakarta.validation-api:3.1.1'
    runtimeOnly 'jakarta.inject:jakarta.inject-api:2.0.1'

    //compileOnly("org.graalvm.nativeimage:svm")

    testImplementation 'io.micronaut:micronaut-http-client-jdk'
    //testImplementation 'io.micronaut:micronaut-http-client'
}

application {
    mainClass.set("com.gluonhq.ignite.micronaut.FXApplication")
    applicationDefaultJvmArgs = ["--enable-native-access=javafx.graphics"]
}
java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

javafx {
//    version = "17.0.13"
//    version = "21.0.7"
//    version = "25.0.4"
    version = "26.0.2"
    platform = 'linux'
    modules = ['javafx.controls', 'javafx.base', 'javafx.graphics', 'javafx.fxml']
}
